<script setup>
console.log("This is my Vue.js code for the client side of the application.");
import { inject, ref, watch } from "vue"

console.log('Before wsClient injection'); // Log before wsClient injection
const wsClient = inject("wsClient");
console.log('After wsClient injection:', wsClient); // Log after wsClient injection
// I am not exactly sure what the following code does. I am not vue or JavaScript expert.


// I will be keeping the names as consistent as possible with the server state variables to fix potential issues in the future.

// This is supposed to be a ref to the number of bins in the histogram, does it work, who really knows, we'll see.
const bins = ref(5);

// This is supposed to be a ref to the file input, does it work, who really knows, we'll see.
const file_input = ref(null);

/*
This is confusing, I apparently need to get the selected column from somewhere, but I never specified that on the server side.
That is up to the user to decide. So I am not exactly sure what this is supposed to do.
Reminder that this is generated by ChatGPT and edited by me, but I have limited knowledge of Vue.js and JavaScript.
I will be keeping the name of the const variable in snake_case.
*/
const selected_option = ref([]);

// This is supposed to be a ref to the column options, does it work, who really knows, we'll see.
// Also I am not sure why in JavaScript there is no such thing as a empty list, but I guess that's just how it is. [] is an empty array in JavaScript.
const selected_column = ref(null);

// I am honestly not quite sure what this does, it was in the example code I was looking at.
// You can find the example code here: https://github.com/Kitware/vtk-web-solutions/blob/master/client-server/vue-client/src/App.vue
// If I had to seriously guess what this is, I would think it is related to html_view as in the server side code, we are setting the html_view to None.
const viewId = ref(null);

// No idea what this is doing, but it comes from the example code I was looking at.
wsClient.getRemote().Trame.getState().then((s) => {
    viewId.value = s.state.viewId;
});

// I think this is what is watching the state of the bins and updating the server with the new value. But I am not sure.
watch(
    bins,
    (value) => {
        wsClient.getRemote().Trame.updateState([
            { key: "bins", value }
        ]);
    }
)

watch(
    selected_column,
    (value) => {
        wsClient.getRemote().Trame.updateState([
            { key: "selectedColumn", value }
        ]);
    }
)
</script>

<template>
    <div style="width: 50vw; height: 50vh;">
        <vtk-remote-view
            v-if="viewId"
            :viewId="viewId"
            :wsClient="wsClient"
        />
        <v-slider
            v-model.number="bins"
            min="1"
            max="100"
            step="1"
            label="Number of Bins"
            style="position: absolute; top: 20px; right: 20px;"
        />
        <v-file-input
            v-model="file_input"
            label="Upload CSV"
            accept=".csv"
            style="position: absolute; top: 60px; right: 20px;"
        />
        <v-select
            v-model="selected_column"
            :items="selected_option"
            label="Select Column"
            style="position: absolute; top: 100px; right: 20px;"
        />
    </div>
</template>