# Generated by Django 5.0.2 on 2024-03-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_datasetdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdescription',
            name='file_path',
            field=models.CharField(default=12, max_length=1024),
            preserve_default=False,
        ),
    ]
