# Generated by Django 5.1 on 2024-08-07 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datastores',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128)),
                ('Type', models.CharField(choices=[('localfs', 'LocalFS'), ('mongodb', 'MongoDB')], editable=False, max_length=32)),
                ('Created', models.DateField(auto_now_add=True)),
                ('Modified', models.DateField(auto_now=True)),
                ('Connected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LocalFSDatastores',
            fields=[
                ('datastores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.datastores')),
                ('Directory_Path', models.CharField(max_length=4096)),
            ],
            bases=('home.datastores',),
        ),
        migrations.CreateModel(
            name='MongoDBDatastores',
            fields=[
                ('datastores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.datastores')),
                ('Host', models.CharField(max_length=128)),
                ('Port', models.IntegerField()),
                ('Username', models.CharField(max_length=128)),
                ('Password', models.CharField(max_length=128)),
                ('Database', models.CharField(max_length=128)),
                ('Collection', models.CharField(max_length=128)),
            ],
            bases=('home.datastores',),
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
                ('Description', models.TextField(null=True)),
                ('Repository', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=16)),
                ('Likes', models.IntegerField(default=0)),
                ('Dislikes', models.IntegerField(default=0)),
                ('Created', models.DateField(auto_now_add=True)),
                ('Modified', models.DateField(auto_now=True)),
                ('Datastore_UUID', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='home.datastores')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user')),
            ],
        ),
    ]
