# Generated by Django 5.1 on 2024-08-07 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsid', models.CharField(max_length=100, null=True)),
                ('did', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('dname', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('repo', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122, null=True)),
                ('password', models.CharField(max_length=122, null=True)),
            ],
        ),
    ]
