# Generated by Django 5.1.3 on 2024-12-12 09:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='_UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
