# Generated by Django 5.1.5 on 2025-01-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_collections_files_collections_dataset_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamserver',
            name='route',
            field=models.CharField(choices=[('basic', 'Basic Histogram'), ('general', 'General Histogram'), ('ood', 'OOD Analyzer')], max_length=50),
        ),
    ]
