# Generated by Django 5.1.5 on 2025-01-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_collections_files_collections_dataset_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinstance',
            name='websocket_path',
        ),
        migrations.AlterField(
            model_name='serverinstance',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serverinstance',
            name='port',
            field=models.IntegerField(),
        ),
    ]
