# Generated by Django 4.1.13 on 2024-08-19 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_datasets_username_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Image_Identifier', models.CharField(max_length=256)),
                ('File_Path', models.CharField(max_length=10004)),
                ('Created', models.DateField(auto_now_add=True)),
                ('Dataset_UUID', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='home.datasets')),
                ('Datastore_UUID', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='home.datastores')),
            ],
        ),
    ]
