# Generated by Django 5.1.5 on 2025-01-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_upstreamserver_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamserver',
            name='route',
            field=models.CharField(max_length=50),
        ),
    ]
