# Generated by Django 5.1.5 on 2025-01-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_upstreamserver_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamserver',
            name='route',
            field=models.CharField(help_text="Route name (e.g., 'histogram1', 'histogram2', 'analyzer1')", max_length=50),
        ),
        migrations.AddIndex(
            model_name='upstreamserver',
            index=models.Index(fields=['route'], name='home_upstre_route_169346_idx'),
        ),
    ]
