# Generated by Django 5.1.5 on 2025-01-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_upstreamserver_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamserver',
            name='route',
            field=models.CharField(choices=[('histogram1', 'Histogram 1'), ('histogram2', 'Histogram 2'), ('histogram3', 'Histogram 3'), ('analyzer1', 'Analyzer 1'), ('basic', 'Basic Histogram'), ('general', 'General Histogram'), ('ood', 'OOD Analyzer')], help_text='Select the route for this server', max_length=50),
        ),
    ]
