# Generated by Django 5.1.5 on 2025-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_upstreamserver_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstreamserver',
            name='route',
            field=models.CharField(choices=[('histogram1', 'Histogram 1'), ('histogram2', 'Histogram 2'), ('histogram3', 'Histogram 3'), ('histogramgeneral1', 'General Histogram 1'), ('histogramgeneral2', 'General Histogram 2'), ('histogramgeneral3', 'General Histogram 3'), ('analyzer1', 'Analyzer 1'), ('analyzer2', 'Analyzer 2'), ('analyzer3', 'Analyzer 3'), ('basic', 'Basic Histogram'), ('general', 'General Histogram'), ('ood', 'OOD Analyzer')], help_text='Select the route for this server', max_length=50),
        ),
    ]
