# Generated by Django 4.1.13 on 2024-08-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_collections_dataset_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='Repository',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16),
            preserve_default=False,
        ),
    ]
