# Generated by Django 4.1.13 on 2024-09-04 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_collections_dataset_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Collections_UUID',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.collections'),
        ),
    ]
