# Generated by Django 5.1.2 on 2024-10-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_files_collections_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('route', models.CharField(choices=[('new', 'New'), ('new2', 'New2')], max_length=50)),
            ],
            options={
                'unique_together': {('ip', 'port', 'route')},
            },
        ),
    ]
